[2023-02-04T02:02:04.774+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: real_estate_data_pipeline.load_data_to_postgres manual__2023-02-04T02:01:56.615751+00:00 [queued]>
[2023-02-04T02:02:04.780+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: real_estate_data_pipeline.load_data_to_postgres manual__2023-02-04T02:01:56.615751+00:00 [queued]>
[2023-02-04T02:02:04.781+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-02-04T02:02:04.781+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2023-02-04T02:02:04.781+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-02-04T02:02:04.789+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): load_data_to_postgres> on 2023-02-04 02:01:56.615751+00:00
[2023-02-04T02:02:04.793+0000] {standard_task_runner.py:54} INFO - Started process 6674 to run task
[2023-02-04T02:02:04.797+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'real_estate_data_pipeline', 'load_data_to_postgres', 'manual__2023-02-04T02:01:56.615751+00:00', '--job-id', '1350', '--raw', '--subdir', 'DAGS_FOLDER/real_estate_dag.py', '--cfg-path', '/tmp/tmphk1cyufy']
[2023-02-04T02:02:04.799+0000] {standard_task_runner.py:83} INFO - Job 1350: Subtask load_data_to_postgres
[2023-02-04T02:02:04.800+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/real_estate_dag.py
[2023-02-04T02:02:05.070+0000] {task_command.py:384} INFO - Running <TaskInstance: real_estate_data_pipeline.load_data_to_postgres manual__2023-02-04T02:01:56.615751+00:00 [running]> on host 9667f615f42a
[2023-02-04T02:02:05.117+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=real_estate_data_pipeline
AIRFLOW_CTX_TASK_ID=load_data_to_postgres
AIRFLOW_CTX_EXECUTION_DATE=2023-02-04T02:01:56.615751+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-04T02:01:56.615751+00:00
[2023-02-04T02:02:05.135+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 94, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 288, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 88, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 70, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 432, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_default` isn't defined
[2023-02-04T02:02:05.140+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=real_estate_data_pipeline, task_id=load_data_to_postgres, execution_date=20230204T020156, start_date=20230204T020204, end_date=20230204T020205
[2023-02-04T02:02:05.146+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1350 for task load_data_to_postgres (The conn_id `postgres_default` isn't defined; 6674)
[2023-02-04T02:02:05.173+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-02-04T02:02:05.188+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
