[2023-02-04T00:55:14.953+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: real_estate_data_pipeline.create_db manual__2023-02-04T00:34:17.812895+00:00 [queued]>
[2023-02-04T00:55:14.965+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: real_estate_data_pipeline.create_db manual__2023-02-04T00:34:17.812895+00:00 [queued]>
[2023-02-04T00:55:14.966+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-02-04T00:55:14.966+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2023-02-04T00:55:14.967+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-02-04T00:55:14.978+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): create_db> on 2023-02-04 00:34:17.812895+00:00
[2023-02-04T00:55:14.983+0000] {standard_task_runner.py:54} INFO - Started process 3310 to run task
[2023-02-04T00:55:14.987+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'real_estate_data_pipeline', 'create_db', 'manual__2023-02-04T00:34:17.812895+00:00', '--job-id', '1306', '--raw', '--subdir', 'DAGS_FOLDER/real_estate_dag.py', '--cfg-path', '/tmp/tmp2jq1ufb9']
[2023-02-04T00:55:14.988+0000] {standard_task_runner.py:83} INFO - Job 1306: Subtask create_db
[2023-02-04T00:55:14.990+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/real_estate_dag.py
[2023-02-04T00:55:15.457+0000] {task_command.py:384} INFO - Running <TaskInstance: real_estate_data_pipeline.create_db manual__2023-02-04T00:34:17.812895+00:00 [running]> on host 9667f615f42a
[2023-02-04T00:55:15.516+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=real_estate_data_pipeline
AIRFLOW_CTX_TASK_ID=create_db
AIRFLOW_CTX_EXECUTION_DATE=2023-02-04T00:34:17.812895+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-04T00:34:17.812895+00:00
[2023-02-04T00:55:15.519+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/real_estate_dag.py", line 69, in create_db
    conn = psycopg2.connect(dbname="housing_market_db", user="postgres", password="postgres", host="localhost")
NameError: name 'psycopg2' is not defined
[2023-02-04T00:55:15.528+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=real_estate_data_pipeline, task_id=create_db, execution_date=20230204T003417, start_date=20230204T005514, end_date=20230204T005515
[2023-02-04T00:55:15.537+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1306 for task create_db (name 'psycopg2' is not defined; 3310)
[2023-02-04T00:55:15.610+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-02-04T00:55:15.641+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
