[2023-02-04T00:17:17.702+0000] {processor.py:156} INFO - Started process (PID=1396) to work on /opt/airflow/dags/ll.py
[2023-02-04T00:17:17.705+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/ll.py for tasks to queue
[2023-02-04T00:17:17.708+0000] {logging_mixin.py:117} INFO - [2023-02-04T00:17:17.708+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/ll.py
[2023-02-04T00:17:18.014+0000] {logging_mixin.py:117} INFO - [2023-02-04T00:17:18.009+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/ll.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ll.py", line 9, in <module>
    df = pd.read_csv(path)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
IsADirectoryError: [Errno 21] Is a directory: '.'
[2023-02-04T00:17:18.022+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/ll.py
[2023-02-04T00:17:18.054+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/ll.py took 0.361 seconds
[2023-02-04T00:17:48.490+0000] {processor.py:156} INFO - Started process (PID=1427) to work on /opt/airflow/dags/ll.py
[2023-02-04T00:17:48.495+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/ll.py for tasks to queue
[2023-02-04T00:17:48.497+0000] {logging_mixin.py:117} INFO - [2023-02-04T00:17:48.497+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/ll.py
[2023-02-04T00:17:48.856+0000] {logging_mixin.py:117} INFO - [2023-02-04T00:17:48.848+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/ll.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ll.py", line 9, in <module>
    df = pd.read_csv(path)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
IsADirectoryError: [Errno 21] Is a directory: '.'
[2023-02-04T00:17:48.858+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/ll.py
[2023-02-04T00:17:48.887+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/ll.py took 0.411 seconds
[2023-02-04T00:18:19.617+0000] {processor.py:156} INFO - Started process (PID=1458) to work on /opt/airflow/dags/ll.py
[2023-02-04T00:18:19.619+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/ll.py for tasks to queue
[2023-02-04T00:18:19.621+0000] {logging_mixin.py:117} INFO - [2023-02-04T00:18:19.621+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/ll.py
[2023-02-04T00:18:19.869+0000] {logging_mixin.py:117} INFO - [2023-02-04T00:18:19.866+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/ll.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ll.py", line 9, in <module>
    df = pd.read_csv(path)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
IsADirectoryError: [Errno 21] Is a directory: '.'
[2023-02-04T00:18:19.870+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/ll.py
[2023-02-04T00:18:19.909+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/ll.py took 0.302 seconds
[2023-02-04T00:18:50.263+0000] {processor.py:156} INFO - Started process (PID=1488) to work on /opt/airflow/dags/ll.py
[2023-02-04T00:18:50.268+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/ll.py for tasks to queue
[2023-02-04T00:18:50.269+0000] {logging_mixin.py:117} INFO - [2023-02-04T00:18:50.269+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/ll.py
[2023-02-04T00:18:50.462+0000] {logging_mixin.py:117} INFO - [2023-02-04T00:18:50.460+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/ll.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ll.py", line 9, in <module>
    df = pd.read_csv(path)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
IsADirectoryError: [Errno 21] Is a directory: '.'
[2023-02-04T00:18:50.464+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/ll.py
[2023-02-04T00:18:50.487+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/ll.py took 0.238 seconds
[2023-02-04T00:19:20.976+0000] {processor.py:156} INFO - Started process (PID=1511) to work on /opt/airflow/dags/ll.py
[2023-02-04T00:19:20.980+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/ll.py for tasks to queue
[2023-02-04T00:19:20.981+0000] {logging_mixin.py:117} INFO - [2023-02-04T00:19:20.981+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/ll.py
[2023-02-04T00:19:21.250+0000] {logging_mixin.py:117} INFO - [2023-02-04T00:19:21.245+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/ll.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ll.py", line 9, in <module>
    df = pd.read_csv(path)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
IsADirectoryError: [Errno 21] Is a directory: '.'
[2023-02-04T00:19:21.250+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/ll.py
[2023-02-04T00:19:21.281+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/ll.py took 0.314 seconds
[2023-02-04T00:19:51.666+0000] {processor.py:156} INFO - Started process (PID=1542) to work on /opt/airflow/dags/ll.py
[2023-02-04T00:19:51.669+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/ll.py for tasks to queue
[2023-02-04T00:19:51.671+0000] {logging_mixin.py:117} INFO - [2023-02-04T00:19:51.671+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/ll.py
[2023-02-04T00:19:51.835+0000] {logging_mixin.py:117} INFO - [2023-02-04T00:19:51.833+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/ll.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ll.py", line 9, in <module>
    df = pd.read_csv(path)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
IsADirectoryError: [Errno 21] Is a directory: '.'
[2023-02-04T00:19:51.836+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/ll.py
[2023-02-04T00:19:51.851+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/ll.py took 0.193 seconds
[2023-02-04T00:20:22.157+0000] {processor.py:156} INFO - Started process (PID=1573) to work on /opt/airflow/dags/ll.py
[2023-02-04T00:20:22.160+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/ll.py for tasks to queue
[2023-02-04T00:20:22.162+0000] {logging_mixin.py:117} INFO - [2023-02-04T00:20:22.161+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/ll.py
[2023-02-04T00:20:22.326+0000] {logging_mixin.py:117} INFO - [2023-02-04T00:20:22.324+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/ll.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ll.py", line 9, in <module>
    df = pd.read_csv(path)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
IsADirectoryError: [Errno 21] Is a directory: '.'
[2023-02-04T00:20:22.327+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/ll.py
[2023-02-04T00:20:22.342+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/ll.py took 0.192 seconds
[2023-02-04T00:20:52.717+0000] {processor.py:156} INFO - Started process (PID=1606) to work on /opt/airflow/dags/ll.py
[2023-02-04T00:20:52.721+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/ll.py for tasks to queue
[2023-02-04T00:20:52.723+0000] {logging_mixin.py:117} INFO - [2023-02-04T00:20:52.722+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/ll.py
[2023-02-04T00:20:52.913+0000] {logging_mixin.py:117} INFO - [2023-02-04T00:20:52.911+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/ll.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ll.py", line 9, in <module>
    df = pd.read_csv(path)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
IsADirectoryError: [Errno 21] Is a directory: '.'
[2023-02-04T00:20:52.914+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/ll.py
[2023-02-04T00:20:52.935+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/ll.py took 0.226 seconds
[2023-02-04T00:21:23.569+0000] {processor.py:156} INFO - Started process (PID=1638) to work on /opt/airflow/dags/ll.py
[2023-02-04T00:21:23.572+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/ll.py for tasks to queue
[2023-02-04T00:21:23.573+0000] {logging_mixin.py:117} INFO - [2023-02-04T00:21:23.573+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/ll.py
[2023-02-04T00:21:23.739+0000] {logging_mixin.py:117} INFO - [2023-02-04T00:21:23.733+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/ll.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ll.py", line 9, in <module>
    df = pd.read_csv(path)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
IsADirectoryError: [Errno 21] Is a directory: '.'
[2023-02-04T00:21:23.740+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/ll.py
[2023-02-04T00:21:23.761+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/ll.py took 0.195 seconds
[2023-02-04T00:21:54.143+0000] {processor.py:156} INFO - Started process (PID=1671) to work on /opt/airflow/dags/ll.py
[2023-02-04T00:21:54.146+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/ll.py for tasks to queue
[2023-02-04T00:21:54.147+0000] {logging_mixin.py:117} INFO - [2023-02-04T00:21:54.147+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/ll.py
[2023-02-04T00:21:54.424+0000] {logging_mixin.py:117} INFO - [2023-02-04T00:21:54.420+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/ll.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ll.py", line 9, in <module>
    df = pd.read_csv(path)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
IsADirectoryError: [Errno 21] Is a directory: '.'
[2023-02-04T00:21:54.425+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/ll.py
[2023-02-04T00:21:54.449+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/ll.py took 0.318 seconds
[2023-02-04T00:22:24.848+0000] {processor.py:156} INFO - Started process (PID=1702) to work on /opt/airflow/dags/ll.py
[2023-02-04T00:22:24.852+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/ll.py for tasks to queue
[2023-02-04T00:22:24.854+0000] {logging_mixin.py:117} INFO - [2023-02-04T00:22:24.854+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/ll.py
[2023-02-04T00:22:25.109+0000] {logging_mixin.py:117} INFO - [2023-02-04T00:22:25.106+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/ll.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ll.py", line 9, in <module>
    df = pd.read_csv(path)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
IsADirectoryError: [Errno 21] Is a directory: '.'
[2023-02-04T00:22:25.110+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/ll.py
[2023-02-04T00:22:25.149+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/ll.py took 0.307 seconds
[2023-02-04T00:22:55.514+0000] {processor.py:156} INFO - Started process (PID=1732) to work on /opt/airflow/dags/ll.py
[2023-02-04T00:22:55.517+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/ll.py for tasks to queue
[2023-02-04T00:22:55.519+0000] {logging_mixin.py:117} INFO - [2023-02-04T00:22:55.518+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/ll.py
[2023-02-04T00:22:55.655+0000] {logging_mixin.py:117} INFO - [2023-02-04T00:22:55.653+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/ll.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ll.py", line 9, in <module>
    df = pd.read_csv(path)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
IsADirectoryError: [Errno 21] Is a directory: '.'
[2023-02-04T00:22:55.657+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/ll.py
[2023-02-04T00:22:55.671+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/ll.py took 0.163 seconds
[2023-02-04T00:23:25.967+0000] {processor.py:156} INFO - Started process (PID=1763) to work on /opt/airflow/dags/ll.py
[2023-02-04T00:23:25.970+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/ll.py for tasks to queue
[2023-02-04T00:23:25.972+0000] {logging_mixin.py:117} INFO - [2023-02-04T00:23:25.971+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/ll.py
[2023-02-04T00:23:26.162+0000] {logging_mixin.py:117} INFO - [2023-02-04T00:23:26.160+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/ll.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/ll.py", line 9, in <module>
    df = pd.read_csv(path)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
IsADirectoryError: [Errno 21] Is a directory: '.'
[2023-02-04T00:23:26.163+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/ll.py
[2023-02-04T00:23:26.178+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/ll.py took 0.215 seconds
