[2023-01-21T10:59:19.555+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: real_estate_data_pipeline.read_csv scheduled__2022-01-20T08:00:00+00:00 [queued]>
[2023-01-21T10:59:19.563+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: real_estate_data_pipeline.read_csv scheduled__2022-01-20T08:00:00+00:00 [queued]>
[2023-01-21T10:59:19.564+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T10:59:19.565+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2023-01-21T10:59:19.567+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T10:59:19.621+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): read_csv> on 2022-01-20 08:00:00+00:00
[2023-01-21T10:59:19.627+0000] {standard_task_runner.py:54} INFO - Started process 3715 to run task
[2023-01-21T10:59:19.644+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'real_estate_data_pipeline', 'read_csv', 'scheduled__2022-01-20T08:00:00+00:00', '--job-id', '968', '--raw', '--subdir', 'DAGS_FOLDER/real_estate_dag.py', '--cfg-path', '/tmp/tmpxhzbcg40']
[2023-01-21T10:59:19.645+0000] {standard_task_runner.py:83} INFO - Job 968: Subtask read_csv
[2023-01-21T10:59:19.647+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/real_estate_dag.py
[2023-01-21T10:59:20.071+0000] {task_command.py:384} INFO - Running <TaskInstance: real_estate_data_pipeline.read_csv scheduled__2022-01-20T08:00:00+00:00 [running]> on host 2fb4a96081a8
[2023-01-21T10:59:20.164+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=real_estate_data_pipeline
AIRFLOW_CTX_TASK_ID=read_csv
AIRFLOW_CTX_EXECUTION_DATE=2022-01-20T08:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-20T08:00:00+00:00
[2023-01-21T10:59:20.169+0000] {logging_mixin.py:117} INFO - False
[2023-01-21T10:59:20.172+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/real_estate_dag.py", line 32, in read_csv
    df = pd.read_csv('sales.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'sales.csv'
[2023-01-21T10:59:20.192+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=real_estate_data_pipeline, task_id=read_csv, execution_date=20220120T080000, start_date=20230121T105919, end_date=20230121T105920
[2023-01-21T10:59:20.204+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 968 for task read_csv ([Errno 2] No such file or directory: 'sales.csv'; 3715)
[2023-01-21T10:59:20.254+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-01-21T10:59:20.291+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-21T11:05:29.026+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: real_estate_data_pipeline.read_csv scheduled__2022-01-20T08:00:00+00:00 [queued]>
[2023-01-21T11:05:29.034+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: real_estate_data_pipeline.read_csv scheduled__2022-01-20T08:00:00+00:00 [queued]>
[2023-01-21T11:05:29.035+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T11:05:29.036+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2023-01-21T11:05:29.036+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T11:05:29.052+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): read_csv> on 2022-01-20 08:00:00+00:00
[2023-01-21T11:05:29.056+0000] {standard_task_runner.py:54} INFO - Started process 4136 to run task
[2023-01-21T11:05:29.064+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'real_estate_data_pipeline', 'read_csv', 'scheduled__2022-01-20T08:00:00+00:00', '--job-id', '1013', '--raw', '--subdir', 'DAGS_FOLDER/real_estate_dag.py', '--cfg-path', '/tmp/tmp0at_kly6']
[2023-01-21T11:05:29.065+0000] {standard_task_runner.py:83} INFO - Job 1013: Subtask read_csv
[2023-01-21T11:05:29.067+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/real_estate_dag.py
[2023-01-21T11:05:29.642+0000] {task_command.py:384} INFO - Running <TaskInstance: real_estate_data_pipeline.read_csv scheduled__2022-01-20T08:00:00+00:00 [running]> on host 2fb4a96081a8
[2023-01-21T11:05:29.797+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=real_estate_data_pipeline
AIRFLOW_CTX_TASK_ID=read_csv
AIRFLOW_CTX_EXECUTION_DATE=2022-01-20T08:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-20T08:00:00+00:00
[2023-01-21T11:05:29.800+0000] {logging_mixin.py:117} INFO - False
[2023-01-21T11:05:29.804+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/real_estate_dag.py", line 32, in read_csv
    df = pd.read_csv('sales.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'sales.csv'
[2023-01-21T11:05:29.838+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=real_estate_data_pipeline, task_id=read_csv, execution_date=20220120T080000, start_date=20230121T110529, end_date=20230121T110529
[2023-01-21T11:05:29.861+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1013 for task read_csv ([Errno 2] No such file or directory: 'sales.csv'; 4136)
[2023-01-21T11:05:29.908+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-01-21T11:05:29.949+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
