[2023-02-04T01:22:27.878+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: real_estate_data_pipeline.create_db manual__2023-02-04T01:17:23.957046+00:00 [queued]>
[2023-02-04T01:22:27.888+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: real_estate_data_pipeline.create_db manual__2023-02-04T01:17:23.957046+00:00 [queued]>
[2023-02-04T01:22:27.889+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-02-04T01:22:27.891+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2023-02-04T01:22:27.891+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-02-04T01:22:27.902+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): create_db> on 2023-02-04 01:17:23.957046+00:00
[2023-02-04T01:22:27.909+0000] {standard_task_runner.py:54} INFO - Started process 4675 to run task
[2023-02-04T01:22:27.914+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'real_estate_data_pipeline', 'create_db', 'manual__2023-02-04T01:17:23.957046+00:00', '--job-id', '1324', '--raw', '--subdir', 'DAGS_FOLDER/real_estate_dag.py', '--cfg-path', '/tmp/tmpp2weokf5']
[2023-02-04T01:22:27.916+0000] {standard_task_runner.py:83} INFO - Job 1324: Subtask create_db
[2023-02-04T01:22:27.917+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/real_estate_dag.py
[2023-02-04T01:22:28.257+0000] {task_command.py:384} INFO - Running <TaskInstance: real_estate_data_pipeline.create_db manual__2023-02-04T01:17:23.957046+00:00 [running]> on host 9667f615f42a
[2023-02-04T01:22:28.313+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=real_estate_data_pipeline
AIRFLOW_CTX_TASK_ID=create_db
AIRFLOW_CTX_EXECUTION_DATE=2023-02-04T01:17:23.957046+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-02-04T01:17:23.957046+00:00
[2023-02-04T01:22:28.314+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/real_estate_dag.py", line 70, in create_db
    conn = psycopg2.connect(dbname="airflow", user="airflow", password="airflow", host="localhost")
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

[2023-02-04T01:22:28.324+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=real_estate_data_pipeline, task_id=create_db, execution_date=20230204T011723, start_date=20230204T012227, end_date=20230204T012228
[2023-02-04T01:22:28.331+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1324 for task create_db (connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
; 4675)
[2023-02-04T01:22:28.371+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-02-04T01:22:28.392+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
