[2023-01-21T10:54:36.274+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: real_estate_data_pipeline.read_csv scheduled__2022-01-20T17:00:00+00:00 [queued]>
[2023-01-21T10:54:36.285+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: real_estate_data_pipeline.read_csv scheduled__2022-01-20T17:00:00+00:00 [queued]>
[2023-01-21T10:54:36.286+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T10:54:36.287+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2023-01-21T10:54:36.288+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T10:54:36.306+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): read_csv> on 2022-01-20 17:00:00+00:00
[2023-01-21T10:54:36.315+0000] {standard_task_runner.py:54} INFO - Started process 3451 to run task
[2023-01-21T10:54:36.329+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'real_estate_data_pipeline', 'read_csv', 'scheduled__2022-01-20T17:00:00+00:00', '--job-id', '958', '--raw', '--subdir', 'DAGS_FOLDER/real_estate_dag.py', '--cfg-path', '/tmp/tmpirw2twz_']
[2023-01-21T10:54:36.333+0000] {standard_task_runner.py:83} INFO - Job 958: Subtask read_csv
[2023-01-21T10:54:36.337+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/real_estate_dag.py
[2023-01-21T10:54:36.834+0000] {task_command.py:384} INFO - Running <TaskInstance: real_estate_data_pipeline.read_csv scheduled__2022-01-20T17:00:00+00:00 [running]> on host 2fb4a96081a8
[2023-01-21T10:54:37.286+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=real_estate_data_pipeline
AIRFLOW_CTX_TASK_ID=read_csv
AIRFLOW_CTX_EXECUTION_DATE=2022-01-20T17:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-20T17:00:00+00:00
[2023-01-21T10:54:37.305+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/real_estate_dag.py", line 27, in read_csv
    df = pd.read_csv('sales.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'sales.csv'
[2023-01-21T10:54:37.350+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=real_estate_data_pipeline, task_id=read_csv, execution_date=20220120T170000, start_date=20230121T105436, end_date=20230121T105437
[2023-01-21T10:54:37.404+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 958 for task read_csv ([Errno 2] No such file or directory: 'sales.csv'; 3451)
[2023-01-21T10:54:37.614+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-01-21T10:54:37.735+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-21T11:00:30.844+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: real_estate_data_pipeline.read_csv scheduled__2022-01-20T17:00:00+00:00 [queued]>
[2023-01-21T11:00:31.023+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: real_estate_data_pipeline.read_csv scheduled__2022-01-20T17:00:00+00:00 [queued]>
[2023-01-21T11:00:31.043+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T11:00:31.057+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2023-01-21T11:00:31.060+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-21T11:00:31.372+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): read_csv> on 2022-01-20 17:00:00+00:00
[2023-01-21T11:00:31.536+0000] {standard_task_runner.py:54} INFO - Started process 3884 to run task
[2023-01-21T11:00:31.661+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'real_estate_data_pipeline', 'read_csv', 'scheduled__2022-01-20T17:00:00+00:00', '--job-id', '1007', '--raw', '--subdir', 'DAGS_FOLDER/real_estate_dag.py', '--cfg-path', '/tmp/tmp3vcnklo2']
[2023-01-21T11:00:31.672+0000] {standard_task_runner.py:83} INFO - Job 1007: Subtask read_csv
[2023-01-21T11:00:31.676+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/real_estate_dag.py
[2023-01-21T11:00:35.759+0000] {task_command.py:384} INFO - Running <TaskInstance: real_estate_data_pipeline.read_csv scheduled__2022-01-20T17:00:00+00:00 [running]> on host 2fb4a96081a8
[2023-01-21T11:00:36.698+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=me
AIRFLOW_CTX_DAG_ID=real_estate_data_pipeline
AIRFLOW_CTX_TASK_ID=read_csv
AIRFLOW_CTX_EXECUTION_DATE=2022-01-20T17:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-20T17:00:00+00:00
[2023-01-21T11:00:36.719+0000] {logging_mixin.py:117} INFO - False
[2023-01-21T11:00:36.735+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/real_estate_dag.py", line 32, in read_csv
    df = pd.read_csv('sales.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: 'sales.csv'
[2023-01-21T11:00:37.049+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=real_estate_data_pipeline, task_id=read_csv, execution_date=20220120T170000, start_date=20230121T110030, end_date=20230121T110037
[2023-01-21T11:00:37.153+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1007 for task read_csv ([Errno 2] No such file or directory: 'sales.csv'; 3884)
[2023-01-21T11:00:38.069+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-01-21T11:00:38.332+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
